/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUpdateProfileRouteImport } from './routes/dashboard/update-profile'
import { Route as DashboardDangerZoneRouteImport } from './routes/dashboard/danger-zone'
import { Route as DashboardCreateBookingRouteImport } from './routes/dashboard/create-booking'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiBookingRouteImport } from './routes/api/booking'
import { Route as ApiAccountRouteImport } from './routes/api/account'
import { Route as DashboardUpdateBookingBookingIdRouteImport } from './routes/dashboard/update-booking.$bookingId'
import { Route as ApiBookingCreateRouteImport } from './routes/api/booking.create'
import { Route as ApiBookingBookingIdRouteImport } from './routes/api/booking.$bookingId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUpdateProfileRoute = DashboardUpdateProfileRouteImport.update({
  id: '/update-profile',
  path: '/update-profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDangerZoneRoute = DashboardDangerZoneRouteImport.update({
  id: '/danger-zone',
  path: '/danger-zone',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreateBookingRoute = DashboardCreateBookingRouteImport.update({
  id: '/create-booking',
  path: '/create-booking',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingRoute = ApiBookingRouteImport.update({
  id: '/api/booking',
  path: '/api/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountRoute = ApiAccountRouteImport.update({
  id: '/api/account',
  path: '/api/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUpdateBookingBookingIdRoute =
  DashboardUpdateBookingBookingIdRouteImport.update({
    id: '/update-booking/$bookingId',
    path: '/update-booking/$bookingId',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiBookingCreateRoute = ApiBookingCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ApiBookingRoute,
} as any)
const ApiBookingBookingIdRoute = ApiBookingBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => ApiBookingRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/api/account': typeof ApiAccountRoute
  '/api/booking': typeof ApiBookingRouteWithChildren
  '/api/profile': typeof ApiProfileRoute
  '/dashboard/create-booking': typeof DashboardCreateBookingRoute
  '/dashboard/danger-zone': typeof DashboardDangerZoneRoute
  '/dashboard/update-profile': typeof DashboardUpdateProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/booking/$bookingId': typeof ApiBookingBookingIdRoute
  '/api/booking/create': typeof ApiBookingCreateRoute
  '/dashboard/update-booking/$bookingId': typeof DashboardUpdateBookingBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/account': typeof ApiAccountRoute
  '/api/booking': typeof ApiBookingRouteWithChildren
  '/api/profile': typeof ApiProfileRoute
  '/dashboard/create-booking': typeof DashboardCreateBookingRoute
  '/dashboard/danger-zone': typeof DashboardDangerZoneRoute
  '/dashboard/update-profile': typeof DashboardUpdateProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/booking/$bookingId': typeof ApiBookingBookingIdRoute
  '/api/booking/create': typeof ApiBookingCreateRoute
  '/dashboard/update-booking/$bookingId': typeof DashboardUpdateBookingBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/api/account': typeof ApiAccountRoute
  '/api/booking': typeof ApiBookingRouteWithChildren
  '/api/profile': typeof ApiProfileRoute
  '/dashboard/create-booking': typeof DashboardCreateBookingRoute
  '/dashboard/danger-zone': typeof DashboardDangerZoneRoute
  '/dashboard/update-profile': typeof DashboardUpdateProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/booking/$bookingId': typeof ApiBookingBookingIdRoute
  '/api/booking/create': typeof ApiBookingCreateRoute
  '/dashboard/update-booking/$bookingId': typeof DashboardUpdateBookingBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/account'
    | '/api/booking'
    | '/api/profile'
    | '/dashboard/create-booking'
    | '/dashboard/danger-zone'
    | '/dashboard/update-profile'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/booking/$bookingId'
    | '/api/booking/create'
    | '/dashboard/update-booking/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/account'
    | '/api/booking'
    | '/api/profile'
    | '/dashboard/create-booking'
    | '/dashboard/danger-zone'
    | '/dashboard/update-profile'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/booking/$bookingId'
    | '/api/booking/create'
    | '/dashboard/update-booking/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/account'
    | '/api/booking'
    | '/api/profile'
    | '/dashboard/create-booking'
    | '/dashboard/danger-zone'
    | '/dashboard/update-profile'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/booking/$bookingId'
    | '/api/booking/create'
    | '/dashboard/update-booking/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAccountRoute: typeof ApiAccountRoute
  ApiBookingRoute: typeof ApiBookingRouteWithChildren
  ApiProfileRoute: typeof ApiProfileRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/update-profile': {
      id: '/dashboard/update-profile'
      path: '/update-profile'
      fullPath: '/dashboard/update-profile'
      preLoaderRoute: typeof DashboardUpdateProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/danger-zone': {
      id: '/dashboard/danger-zone'
      path: '/danger-zone'
      fullPath: '/dashboard/danger-zone'
      preLoaderRoute: typeof DashboardDangerZoneRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/create-booking': {
      id: '/dashboard/create-booking'
      path: '/create-booking'
      fullPath: '/dashboard/create-booking'
      preLoaderRoute: typeof DashboardCreateBookingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking': {
      id: '/api/booking'
      path: '/api/booking'
      fullPath: '/api/booking'
      preLoaderRoute: typeof ApiBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account': {
      id: '/api/account'
      path: '/api/account'
      fullPath: '/api/account'
      preLoaderRoute: typeof ApiAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/update-booking/$bookingId': {
      id: '/dashboard/update-booking/$bookingId'
      path: '/update-booking/$bookingId'
      fullPath: '/dashboard/update-booking/$bookingId'
      preLoaderRoute: typeof DashboardUpdateBookingBookingIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/booking/create': {
      id: '/api/booking/create'
      path: '/create'
      fullPath: '/api/booking/create'
      preLoaderRoute: typeof ApiBookingCreateRouteImport
      parentRoute: typeof ApiBookingRoute
    }
    '/api/booking/$bookingId': {
      id: '/api/booking/$bookingId'
      path: '/$bookingId'
      fullPath: '/api/booking/$bookingId'
      preLoaderRoute: typeof ApiBookingBookingIdRouteImport
      parentRoute: typeof ApiBookingRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardCreateBookingRoute: typeof DashboardCreateBookingRoute
  DashboardDangerZoneRoute: typeof DashboardDangerZoneRoute
  DashboardUpdateProfileRoute: typeof DashboardUpdateProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardUpdateBookingBookingIdRoute: typeof DashboardUpdateBookingBookingIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCreateBookingRoute: DashboardCreateBookingRoute,
  DashboardDangerZoneRoute: DashboardDangerZoneRoute,
  DashboardUpdateProfileRoute: DashboardUpdateProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardUpdateBookingBookingIdRoute: DashboardUpdateBookingBookingIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiBookingRouteChildren {
  ApiBookingBookingIdRoute: typeof ApiBookingBookingIdRoute
  ApiBookingCreateRoute: typeof ApiBookingCreateRoute
}

const ApiBookingRouteChildren: ApiBookingRouteChildren = {
  ApiBookingBookingIdRoute: ApiBookingBookingIdRoute,
  ApiBookingCreateRoute: ApiBookingCreateRoute,
}

const ApiBookingRouteWithChildren = ApiBookingRoute._addFileChildren(
  ApiBookingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAccountRoute: ApiAccountRoute,
  ApiBookingRoute: ApiBookingRouteWithChildren,
  ApiProfileRoute: ApiProfileRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
